---
title: "İSTANBUL DEPREMİ RİSK SENARYOSU"
author: 
  - MERVENUR BÜLBÜL[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 19080207, [Github Repo](https://github.com/mervebulbul1/19080207)



# Giriş

*Bilim insanlarının 2030 yılına kadar gerçekleşmesini beklediği İstanbul depremi hakkında risk analizi araştırma konumdur.Veri setimi İstanbul Büyükşehir Belediye sitesinden buldum.Verimde yer alan gözlemler İstanbul'un ilçeleri değişkenler ise hasar derecesine göre binalar,can kaybı yaralı sayısı,doğal gaz borusu ve içme suyu borusu hasarları atık su boru hasarı ve geçici barınma.*




## Çalışmanın Amacı
 Türkiye bulunduğu konum itibariyle arazilerinin % 42’si birinci dereceden, % 24’ü ikinci dereceden ve % 18’i ise üçüncü dereceden deprem bölgesi içinde yer almaktadır.istanbul'da birinci dereceden deprem bölgesinde yer almaktadır.Türkiye'yi doğu batı yönünde kuşatan yaklaşık 1500 km uzunluğundaki Kuzey Anadolu Fayı (KAF)ın İstanbul 'un güneyinde Marmara Denizi içindeki yaklaşık 200 kilometrelk kısmının kareket geçmesi ile oluşacak depremin büyüklüğünün 7.7 ve 2030 yılına kadar gerçekleşme olasılığının %62 olduğu hesaplanmıştır.
Genel anlamda risk, herhangi bir tehlikenin meydana gelme olasılığı ile bu tehlikenin neden olacağı sonuçların bileşkesidir. Başka bir değişle, risk düzeyi tehlikenin büyüklüğü ve etkilenen elemanların savunmasızlığıyla orantılıdır.
Sismik tehlike analizinde kullanılan veri tabanı depremin olma olasılığı, olası büyüklüğü ve yakın çevresinde yaratacağı şiddet gibi bilgilerden oluşmaktadır. Sismik risk analizinin çıktıları ise depreme bağlı can kayıpları başta olmak üzere
yollar, köprüler, barajlar ve sanayi tesisleri gibi yapıların zarar görmesi nedeniyle oluşacak maddi kayıpların tahminlerini kapsamaktadır.
KAF faaliyetlerinin tarihi kayıtlarına göre, İstanbul iki büyük deprem yaşamıştır.
1509 ve 1766'da tüm şehri yerle bir eden depremlerler olmuştur.*
Bu çalışmayla olası İstanbul depremi sonucunda meydana gelebilecek hasarların neler olabileceği araştırılacaktır.


## Literatür
  Depremin yol açacağı hasar ve can kaybının tahmini,depremin zararlarının öngörülmesi açısından çok önemlidir.Deprem riskini etkileyen faktörler; deprem tehlikesi,
arazi kullanımı, demografik yapı ve ekonomik yapı olarak 4 başlık altında değerlendirilebilir.Deprem tehlikesi, başta depremin büyüklüğü olmak üzere, deprem dalgalarının farklı zeminlerdeki yayılım hızları ve yarattıkları ivme değerleriyle ölçülebilmektedir. Ayrıca, depremin tetiklediği zemin sıvılaşması, heyelan ve tsunami gibi diğer tehditler de deprem tehlikesi kapsamında incelenmektedir. Arazi kullanım şekilleri ve yapısı, etkilenmesi beklenen bölgede yaşayan nüfusun demografik durumu ve yine bu bölgenin ekonomik gücü, deprem riskinin değerlendirilmesinde hasar görebilirlik modülünü oluşturmaktadır. Arazi kullanımını oluşturan değişkenler sadece farklı kullanım dokularını değil, bu dokuları oluşturan öğelerin deprem karşısındaki davranış biçimlerini de içermektedir.Bina yoğunluğu, yapı tarzı, kat yükseklikleri ve altyapı sisteminin farklı noktalarındaki farklı özellikleri, yapılaşmış çevrenin deprem riski açısından değerlendirilmesinde temel başlıkları oluşturmaktadır. Genel arazi kullanım  dokusu göz önüne alındığında barınma, kamusal hizmetler,ticaret, sanayi ve altyapı sistemleri şeklinde bir gruplama yapılabilir.(@kundak2010istanbul)
   
   Kandilli Rasathanesi ve Deprem Araştırma Enstitüsü'nün yaptığı tahminlere göre,7,5 büyüklüğünde bir depremin gece meydana gelmesi durumunda, ortalama can kaybının 14.150 civarında olacak ve ağır yaralı sayısı 8.100 civarında olacak. Eğer
Gündüz saatlerinde meydana gelen depremde 12.400 kişinin ölebileceği ve 7.450 kişinin ağır yaralanabileceği tahmin edilmektedir.7,5 büyüklüğünde, İstanbul'daki binaların %26'sının hafif,%13 orta, %3 ağır ve %1 çok ağır hasarlı olduğunun tahmini üzerine 26,04 milyar dolar ekonomik kayba neden olabilir.(@csimcsekistanbul)

## Kaynakça
Şimşek, P., & Gündüz, A. İstanbul’u Büyük Bir Deprem Bekliyor: Mini Derleme.

KUNDAK, S., & TÜRKOĞLU, H. (2010). İstanbul'da deprem riski analizi. İTÜDERGİSİ/a, 6(2).

Kundak, S., & Handan, T. (2005). Assessment of seismic risk in Istanbul.

Kundak, S., & Dülger-Türkoğlu, H. (2007). Evaluation of Earthquake Risk Parameters in the Historical Site of Istanbul. ARI (The Bulletin of the Istanbul Technical University), 55(1), 53-66.


\newpage
# Kaynakça {#references}
<div id="refs"></div>

